dist: xenial
language: python
python: "3.7"
cache: pip


env:
  matrix:
  - TOXENV: pre-commit
  - TOXENV: build-docs


before_install:
- python -m pip install tox
install:
- tox --notest

script:
- tox
